baseURL = "https://www.nicolas-gomes.com/"
languageCode = "en-us"
title = "Nicolas Gomes de Oliveira"
theme = "beautifulhugo"
enableEmoji = true
disqusShortname = "nicolas-gomes"
googleAnalytics = "UA-97863234-2"

[Params]
  comments = true
  favicon = "/favicon-32x32.png"
  logo = "/site-feature-image.png"
  description = "Hello, I'm a web developer interested in code architecture"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    title = "about me"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "blog section"
    url = "/posts/"
    weight = -120